[package]
name = "rustbound-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ctrlc = "3.5.2"
md-5 = "0.11.0"
rustbound-protocol = { path = "../rustbound-protocol" }

[dev-dependencies]
rustbound-conformance = { path = "../rustbound-conformance" }
rustbound-server = { path = "." }

[lib]
name = "rustbound_server"
path = "src/lib.rs"

[lints]
workspace = true
