[package]
name = "rustbound-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rustbound-protocol = { path = "../rustbound-protocol" }

[dev-dependencies]
rustbound-server = { path = "." }

[lib]
name = "rustbound_server"
path = "src/lib.rs"

[lints]
workspace = true
